language: objective-c

osx_image: xcode7.3

before_install:
    - pod --version
    - pod setup --silent > /dev/null
    - pod repo update --silent

script:
    - pod install
    - xctool -workspace CDOJ-IOS.xcworkspace -scheme 'CDOJ-IOS' -sdk ipadsimulator ONLY_ACTIVE_ARCH=NO
